local E, L, V, P, G = unpack(select(2, ...)); --Import: Engine, Locales, PrivateDB, ProfileDB, GlobalDB

P.gridSize = 100
P.farmSize = 340

--Core
P['general'] = {
	["taintLog"] = false,
	["stickyFrames"] = true,
	['loginmessage'] = false,
	["interruptAnnounce"] = "NONE",
	["autoRepair"] = "GUILD",
	['autoRoll'] = false,
	['vendorGrays'] = true,
	['autoAcceptInvite'] = true,
	['bottomPanel'] = false,
	["hideErrorFrame"] = true,
	['enhancedPvpMessages'] = true,
	['objectiveFrameHeight'] = 600,
	['bonusObjectivePosition'] = "LEFT",
	["talkingHeadFrameScale"] = 0.6,
	['afk'] = true,
	["fontSize"] = 12,
	["font"] = "Arial Narrow",
	["bordercolor"] = { r = .1,g = .1,b = .1 },
	["backdropcolor"] = { r = 0.18,g = 0.18,b = 0.18 },
	["backdropfadecolor"] = { r = .054,g = .054,b = .054, a = 0.8 },
	["valuecolor"] = {r = 196/255,g = 30/255,b = 60/255},

	['minimap'] = {
		['size'] = 200,
		['locationText'] = 'MOUSEOVER',
		['icons'] = {
			['classHall'] = {
				['scale'] = 0.8,
				['position'] = "BOTTOMLEFT",
				['xOffset'] = 0,
				['yOffset'] = 0,
				["hide"] = true,
			},
			['calendar'] = {
				['scale'] = 1,
				['position'] = "TOPRIGHT",
				['xOffset'] = 0,
				['yOffset'] = 0,
				["hide"] = true,
			},
			['mail'] = {
				['scale'] = 1,
				['position'] = "TOPRIGHT",
				['xOffset'] = 3,
				['yOffset'] = 4,
			},
			['lfgEye'] = {
				['scale'] = 1,
				['position'] = "BOTTOMRIGHT",
				['xOffset'] = 3,
				['yOffset'] = 0,
			},
			['difficulty'] = {
				['scale'] = 1,
				['position'] = "TOPLEFT",
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['challengeMode'] = {
				['scale'] = 1,
				['position'] = "TOPLEFT",
				['xOffset'] = 8,
				['yOffset'] = -8,
			},
			['vehicleLeave'] = {
				['size'] = 26,
				['position'] = "BOTTOMLEFT",
				['xOffset'] = 2,
				['yOffset'] = 2,
				["hide"] = false,
			},
		}
	},
	['threat'] = {
		['enable'] = true,
		['position'] = 'RIGHTCHAT',
		['textSize'] = 12,
	},
	['totems'] = {
		['enable'] = true,
		['growthDirection'] = 'HORIZONTAL',
		['sortDirection'] = 'ASCENDING',
		['size'] = 33,
		['spacing'] = 2,
	},
	['kittys'] = false
};

P['databars'] = {
	['experience'] = {
		['enable'] = true,
		['width'] = 204,
		['height'] = 12,
		['textFormat'] = 'NONE',
		['textSize'] = 12,
		['mouseover'] = false,
		['orientation'] = 'HORIZONTAL',
		["reverseFill"] = false,
		["hideAtMaxLevel"] = false,
		["hideInVehicle"] = false,
	},
	['reputation'] = {
		['enable'] = true,
		['width'] = 204,
		['height'] = 12,
		['textFormat'] = 'NONE',
		['textSize'] = 12,
		['mouseover'] = false,
		['orientation'] = 'HORIZONTAL',
		["reverseFill"] = false,
		["hideInVehicle"] = false,
	},
	['artifact'] = {
		['enable'] = true,
		['width'] = 204,
		['height'] = 12,
		['textFormat'] = 'NONE',
		['textSize'] = 12,
		['mouseover'] = false,
		['orientation'] = 'HORIZONTAL',
		["reverseFill"] = false,
		["hideInVehicle"] = false,
	},
	['honor'] = {
		['enable'] = true,
		['width'] = 204,
		['height'] = 12,
		['textFormat'] = 'NONE',
		['textSize'] = 12,
		['mouseover'] = false,
		['orientation'] = 'HORIZONTAL',
		["reverseFill"] = false,
		["hideInVehicle"] = false,
	},
};

--Bags
P['bags'] = {
	['sortInverted'] = true,
	['xOffset'] = 0,
	['yOffset'] = 113,
	['xOffsetBank'] = 986,
	['yOffsetBank'] = -24,
	['bagSize'] = 32,
	['bankSize'] = 32,
	['alignToChat'] = false,
	['bagWidth'] = 407,
	['bankWidth'] = 520,
	['currencyFormat'] = 'ICON',
	['moneyFormat'] = 'BLIZZARD',
	['moneyCoins'] = true,
	["junkIcon"] = true,
	['ignoreItems'] = '',
	['itemLevel'] = true,
	['itemLevelThreshold'] = 1,
	['itemLevelFont'] = 'AgencyFB Bold',
	['itemLevelFontSize'] = 12,
	['itemLevelFontOutline'] = "OUTLINE",
	["countFont"] = 'AgencyFB Bold',
	["countFontSize"] = 12,
	["countFontOutline"] = "OUTLINE",
	["countFontColor"] = {r = 1, g = 1, b = 1},
	['bagBar'] = {
		['growthDirection'] = 'VERTICAL',
		['sortDirection'] = 'ASCENDING',
		['size'] = 33,
		['spacing'] = 2,
		['showBackdrop'] = true,
		['mouseover'] = false,
	},
};

--NamePlate
P["nameplates"] = {
	["statusbar"] = "Aluminium",
	['font'] = 'AgencyFB Bold',
	['fontSize'] = 12,
	['fontOutline'] = 'OUTLINE',
	['useTargetScale'] = true,
	['targetScale'] = 1.15,
	['nonTargetTransparency'] = 0.35,
	["motionType"] =  "OVERLAP",
	["onlyShowTarget"] = false,
	["lowHealthThreshold"] = 0.4,
	["classbar"] = {
		["enable"] = true,
		["attachTo"] = "TARGET",
		["position"] = "ABOVE"
	},
	['castColor'] = { r = 1,g = 208/255,b = 0 },
	['castNoInterruptColor'] = { r = 0.78, g = 0.25, b = 0.25 },
	['reactions'] = {
		["tapped"] = {r = 0.6, g = 0.6, b = 0.6},
		["good"] = {r = 75/255,  g = 175/255, b = 76/255},
		["neutral"] = { r = 218/255, g = 197/255, b = 92/255 },
		["bad"] = { r = 0.78, g = 0.25, b = 0.25 },
		["offline"] = {r = 0.3, g = 0.3, b = 0.3},
	},
	['threat'] = {
		["goodColor"] = {r = 75/255,  g = 175/255, b = 76/255},
		["badColor"] = {r = 0.78, g = 0.25, b = 0.25},
		["goodTransition"] = { r = 218/255, g = 197/255, b = 92/255 },
		["badTransition"] ={ r = 235/255, g = 163/255, b = 40/255 },
		["beingTankedByTankColor"] = {r =.8, g = 0.1,b = 1},
		["beingTankedByTank"] = true,
		["goodScale"] = 0.8,
		["badScale"] = 1.2,
	},

	['units'] = {
		['PLAYER'] = {
			['enable'] = false,
			["alwaysShow"] = false,
			['healthbar'] = {
				['enable'] = true,
				['height'] = 10,
				['width'] = 150,
				['healPrediction'] = true,
				['glowStyle'] = "TARGET_THREAT",
				['text'] = {
					['enable'] = false,
					['format'] = 'CURRENT',
				}
			},
			['showName'] = false,
			['showLevel'] = false,
			['powerbar'] = {
				['enable'] = true,
				['costPrediction'] = true,
				['height'] = 8,
				['text'] = {
					['enable'] = false,
					['format'] = 'CURRENT',
				}
			},
			['castbar'] = {
				['enable'] = true,
				['height'] = 8,
			},
			['buffs'] = {
				['enable'] = true,
				['numAuras'] = 4,
				['baseHeight'] = 18,
				['filters'] = {
					['personal'] = true,
					['boss'] = true,
					['maxDuration'] = 120,
					['filter'] = 'TurtleBuffs'
				},
			},
			['debuffs'] = {
				['enable'] = true,
				['numAuras'] = 4,
				['baseHeight'] = 18,
				['filters'] = {
					['personal'] = true,
					['boss'] = true,
					['maxDuration'] = 120,
					['filter'] = 'CCDebuffs'
				},
			},
		},
		['HEALER'] = {
			['healthbar'] = {
				['enable'] = true,
				['height'] = 10,
				['width'] = 150,
				['healPrediction'] = true,
				['glowStyle'] = "TARGET_THREAT",
				['text'] = {
					['enable'] = false,
					['format'] = 'CURRENT',
				}
			},
			['showName'] = true,
			['showLevel'] = false,
			['powerbar'] = {
				['enable'] = true,
				['costPrediction'] = true,
				['height'] = 8,
				['text'] = {
					['enable'] = false,
					['format'] = 'CURRENT',
				}
			},
			['castbar'] = {
				['enable'] = true,
				['height'] = 8,
			},
			['buffs'] = {
				['enable'] = true,
				['numAuras'] = 4,
				['baseHeight'] = 18,
				['filters'] = {
					['personal'] = true,
					['boss'] = true,
					['maxDuration'] = 120,
					['filter'] = 'TurtleBuffs'
				},
			},
			['debuffs'] = {
				['enable'] = true,
				['numAuras'] = 4,
				['baseHeight'] = 18,
				['filters'] = {
					['personal'] = true,
					['boss'] = true,
					['maxDuration'] = 120,
					['filter'] = 'CCDebuffs'
				},
			},
		},
		['FRIENDLY_PLAYER'] = {
			["minions"] = false,
			['healthbar'] = {
				['enable'] = false,
				['height'] = 10,
				['width'] = 150,
				['healPrediction'] = true,
				['glowStyle'] = "TARGET_THREAT",
				['text'] = {
					['enable'] = false,
					['format'] = 'CURRENT',
				}
			},
			['showName'] = true,
			['showLevel'] = false,
			['powerbar'] = {
				['enable'] = false,
				['costPrediction'] = true,
				['height'] = 8,
				['baseHeight'] = 18,
				['text'] = {
					['enable'] = false,
					['format'] = 'CURRENT',
				}
			},
			['castbar'] = {
				['enable'] = true,
				['height'] = 8,
			},
			['buffs'] = {
				['enable'] = true,
				['numAuras'] = 4,
				['filters'] = {
					['personal'] = true,
					['boss'] = true,
					['maxDuration'] = 120,
					['filter'] = 'TurtleBuffs'
				},
			},
			['debuffs'] = {
				['enable'] = true,
				['numAuras'] = 4,
				['baseHeight'] = 18,
				['filters'] = {
					['personal'] = true,
					['boss'] = true,
					['maxDuration'] = 120,
					['filter'] = 'CCDebuffs'
				},
			},
		},
		['ENEMY_PLAYER'] = {
			["minions"] = false,
			["markHealers"] = true,
			['healthbar'] = {
				['enable'] = true,
				['height'] = 10,
				['width'] = 150,
				['healPrediction'] = true,
				['glowStyle'] = "TARGET_THREAT",
				['text'] = {
					['enable'] = false,
					['format'] = 'CURRENT',
				}
			},
			['showName'] = true,
			['showLevel'] = true,
			['powerbar'] = {
				['enable'] = false,
				['costPrediction'] = true,
				['height'] = 8,
				['text'] = {
					['enable'] = false,
					['format'] = 'CURRENT',
				}
			},
			['castbar'] = {
				['enable'] = true,
				['height'] = 8,
			},
			['buffs'] = {
				['enable'] = true,
				['numAuras'] = 4,
				['baseHeight'] = 18,
				['filters'] = {
					['personal'] = true,
					['boss'] = true,
					['maxDuration'] = 120,
					['filter'] = 'TurtleBuffs'
				},
			},
			['debuffs'] = {
				['enable'] = true,
				['numAuras'] = 4,
				['baseHeight'] = 18,
				['filters'] = {
					['personal'] = true,
					['boss'] = true,
					['maxDuration'] = 120,
					['filter'] = 'CCDebuffs'
				},
			},
		},
		['FRIENDLY_NPC'] = {
			['healthbar'] = {
				['enable'] = false,
				['height'] = 10,
				['width'] = 150,
				['healPrediction'] = true,
				['glowStyle'] = "TARGET_THREAT",
				['text'] = {
					['enable'] = false,
					['format'] = 'CURRENT',
				}
			},
			['showName'] = true,
			['showLevel'] = true,
			['powerbar'] = {
				['enable'] = false,
				['costPrediction'] = true,
				['height'] = 8,
				['text'] = {
					['enable'] = false,
					['format'] = 'CURRENT',
				}
			},
			['castbar'] = {
				['enable'] = false,
				['height'] = 8,
			},
			['buffs'] = {
				['enable'] = true,
				['numAuras'] = 4,
				['baseHeight'] = 18,
				['filters'] = {
					['personal'] = true,
					['boss'] = true,
					['maxDuration'] = 120,
					['filter'] = 'TurtleBuffs'
				},
			},
			['debuffs'] = {
				['enable'] = true,
				['numAuras'] = 4,
				['baseHeight'] = 18,
				['filters'] = {
					['personal'] = true,
					['boss'] = true,
					['maxDuration'] = 120,
					['filter'] = 'CCDebuffs'
				},
			},
		},
		['ENEMY_NPC'] = {
			["minors"] = true,
			['healthbar'] = {
				['enable'] = true,
				['height'] = 8,
				['width'] = 140,
				['healPrediction'] = true,
				['glowStyle'] = "TARGET_THREAT",
				['text'] = {
					['enable'] = false,
					['format'] = 'CURRENT',
				}
			},
			['showName'] = true,
			['showLevel'] = true,
			['powerbar'] = {
				['enable'] = false,
				['costPrediction'] = true,
				['height'] = 8,
				['text'] = {
					['enable'] = false,
					['format'] = 'CURRENT',
				}
			},
			['castbar'] = {
				['enable'] = true,
				['height'] = 6,
			},
			['buffs'] = {
				['enable'] = true,
				['numAuras'] = 8,
				['baseHeight'] = 12,
				['filters'] = {
					['personal'] = true,
					['boss'] = true,
					['maxDuration'] = 120,
					['filter'] = 'TurtleBuffs'
				},
			},
			['debuffs'] = {
				['enable'] = true,
				['numAuras'] = 8,
				['baseHeight'] = 12,
				['filters'] = {
					['personal'] = true,
					['boss'] = true,
					['maxDuration'] = 120,
					['filter'] = 'CCDebuffs'
				},
			},
		},
	},
};

--Auras
P['auras'] = {
	['font'] = 'AgencyFB Bold',
	['fontSize'] = 12,
	['fontOutline'] = 'OUTLINE',
	['countYOffset'] = 0,
	['countXOffset'] = 0,
	['timeYOffset'] = 0,
	['timeXOffset'] = 0,
	['fadeThreshold'] = 5,
	['buffs'] = {
		['growthDirection'] = 'RIGHT_DOWN',
		['wrapAfter'] = 12,
		['maxWraps'] = 3,
		['horizontalSpacing'] = 6,
		['verticalSpacing'] = 16,
		['sortMethod'] = "TIME",
		['sortDir'] = '-',
		['seperateOwn'] = 1,
		['size'] = 32,
	},
	['debuffs'] = {
		['growthDirection'] = 'RIGHT_DOWN',
		['wrapAfter'] = 12,
		['maxWraps'] = 1,
		['horizontalSpacing'] = 6,
		['verticalSpacing'] = 16,
		['sortMethod'] = "TIME",
		['sortDir'] = '-',
		['seperateOwn'] = 1,
		['size'] = 32,
	},
}

--Chat
P['chat'] = {
	['lockPositions'] = true,
	['url'] = true,
	['shortChannels'] = false,
	['hyperlinkHover'] = true,
	['throttleInterval'] = 45,
	['scrollDownInterval'] = 15,
	['fade'] = true,
	['font'] = 'AgencyFB Bold',
	['fontOutline'] = 'OUTLINE',
	['sticky'] = true,
	['emotionIcons'] = true,
	['keywordSound'] = 'None',
	['whisperSound'] = 'Whisper Alert',
	["noAlertInCombat"] = false,
	['chatHistory'] = false,
	['lfgIcons'] = true,
	["timeStampFormat"] = 'NONE',
	['keywords'] = '%MYNAME%, DecUI',
	['separateSizes'] = true,
	['panelWidth'] = 407,
	['panelHeight'] = 94,
	['panelWidthRight'] = 407,
	['panelHeightRight'] = 94,
	['panelBackdropNameLeft'] = '',
	['panelBackdropNameRight'] = '',
	['panelBackdrop'] = 'SHOWBOTH',
	['panelTabBackdrop'] = true,
	['panelTabTransparency'] = true,
	['editBoxPosition'] = 'ABOVE_CHAT',
	['fadeUndockedTabs'] = true,
	['fadeTabsNoBackdrop'] = true,
	["useAltKey"] = false,
	["classColorMentionsChat"] = true,
	['tabFont'] = 'AgencyFB Bold',
	['tabFontSize'] = 12,
	['tabFontOutline'] = 'OUTLINE',
}

--Datatexts
P['datatexts'] = {
	['font'] = 'AgencyFB Bold',
	['fontSize'] = 12,
	['fontOutline'] = 'OUTLINE',
	["wordWrap"] = false,
	['panels'] = {
		['LeftChatDataPanel'] = {
			['left'] = 'Guild',
			['middle'] = 'System',
			['right'] = 'Friends',
		},
		['RightChatDataPanel'] = {
			['left'] = 'Bags',
			['middle'] = 'Durability',
			['right'] = 'Time',
		},
		['LeftMiniPanel'] = 'DPS',
		['RightMiniPanel'] = 'HPS',
		['BottomMiniPanel'] = '',
		['TopMiniPanel'] = '',
		['BottomLeftMiniPanel'] = '',
		['BottomRightMiniPanel'] = '',
		['TopRightMiniPanel'] = '',
		['TopLeftMiniPanel'] = '',
	},
	['localtime'] = true,
	['time24'] = false,
	['battleground'] = true,
	['panelTransparency'] = false,
	['goldFormat'] = 'BLIZZARD',
	['goldCoins'] = false,
	["noCombatClick"] = false,
	["noCombatHover"] = false,

	--Enabled/Disabled Panels
	['minimapPanels'] = true,
	['leftChatPanel'] = true,
	['rightChatPanel'] = true,
	["minimapTop"] = false,
	["minimapTopLeft"] = false,
	["minimapTopRight"] = false,
	["minimapBottom"] = false,
	["minimapBottomLeft"] = false,
	["minimapBottomRight"] = false,
}

--Tooltip
P['tooltip'] = {
	['cursorAnchor'] = false,
	['targetInfo'] = true,
	['playerTitles'] = true,
	['guildRanks'] = true,
	['inspectInfo'] = true,
	['itemCount'] = false,
	['spellID'] = true,
	["font"] = "Arial Narrow",
	["fontOutline"] = "OUTLINE",
	["headerFontSize"] = 12,
	["textFontSize"] = 12,
	["smallTextFontSize"] = 12,
	['visibility'] = {
		['unitFrames'] = 'NONE',
		["bags"] = "NONE",
		["actionbars"] = "NONE",
		['combat'] = false
	},
	['healthBar'] = {
		['text'] = true,
		['height'] = 13,
		['font'] = 'AgencyFB Bold',
		['fontSize'] = 12,
	},
	["useCustomFactionColors"] = false,
	["factionColors"] = {
		["1"] = {r = 0.8, g = 0.3, b = 0.22},
		["2"] = {r = 0.8, g = 0.3, b = 0.22},
		["3"] = {r = 0.75, g = 0.27, b = 0},
		["4"] = {r = 0.9, g = 0.7, b = 0},
		["5"] = {r = 0, g = 0.6, b = 0.1},
		["6"] = {r = 0, g = 0.6, b = 0.1},
		["7"] = {r = 0, g = 0.6, b = 0.1},
		["8"] = {r = 0, g = 0.6, b = 0.1},
	}
}
--UnitFrame
P['unitframe'] = {
	['smoothbars'] = true,
	['statusbar'] = "Aluminium",
	['font'] = 'AgencyFB Bold',
	['fontSize'] = 12,
	['fontOutline'] = 'OUTLINE',
	['OORAlpha'] = 0.35,
	['debuffHighlighting'] = 'FILL',
	["smartRaidFilter"] = true,
	['targetOnMouseDown'] = true,
	["auraBlacklistModifier"] = "SHIFT",
	["thinBorders"] = false,
	['colors'] = {
		['healthclass'] = true,
		['forcehealthreaction'] = false,
		['powerclass'] = false,
		['colorhealthbyvalue'] = true,
		['customhealthbackdrop'] = true,
		['useDeadBackdrop'] = false,
		['classbackdrop'] = false,
		['auraBarByType'] = true,
		['auraBarTurtle'] = true,
		['auraBarTurtleColor'] = {r = 143/255, g = 101/255, b = 158/255},
		['transparentHealth'] = true,
		['transparentPower'] = true,
		['transparentCastbar'] = true,
		['transparentAurabars'] = true,
		['castColor'] = { r = .31,g = .31,b = .31 },
		['castNoInterrupt'] = { r = 0.78, g = 0.25, b = 0.25 },
		['castClassColor'] = true,
		['castReactionColor'] = false,
		['health'] = { r = .31,g = .31,b = .31 },
		['health_backdrop'] = { r = .01,g = .01,b = .01 },
		['health_backdrop_dead'] = { r = .01,g = .01,b = .01 },
		['tapped'] = { r = 0.55, g = 0.57, b = 0.61},
		['disconnected'] = { r = 0.84, g = 0.75, b = 0.65},
		['auraBarBuff'] = P.general.bordercolor,
		['auraBarDebuff'] = {r = 0.8, g = 0.1, b = 0.1},
		['power'] = {
			["MANA"] = {r = 0.31, g = 0.45, b = 0.63},
			["RAGE"] = {r = 0.78, g = 0.25, b = 0.25},
			["FOCUS"] = {r = 0.71, g = 0.43, b = 0.27},
			["ENERGY"] = {r = 0.65, g = 0.63, b = 0.35},
			["RUNIC_POWER"] = {r = 0, g = 0.82, b = 1},
			["PAIN"] = {r = 225/255, g = 225/255, b = 225/255},
			["FURY"] = {r = 227/255, g = 126/255, b = 39/255},
			["LUNAR_POWER"] = {r = .9, g = .86, b = .12},
			["INSANITY"] = {r = 0.55, g = 0.14, b = 0.69},

			["MAELSTROM"] = {r = 0, g = 0.5, b = 1},
		},
		['reaction'] = {
			['BAD'] = { r = 0.78, g = 0.25, b = 0.25 },
			['NEUTRAL'] = { r = 218/255, g = 197/255, b = 92/255 },
			['GOOD'] = { r = 75/255, g = 175/255, b = 76/255 },
		},
		['healPrediction'] = {
			['personal'] = {r = 0, g = 1, b = 0.5, a = 0.25},
			['others'] = {r = 0, g = 1, b = 0, a = 0.25},
			['absorbs'] = {r = 1, g = 1, b = 0, a = 0.25}
		},
		['classResources'] = {
			['bgColor'] = {r = 0.1,g = 0.1,b = 0.1, a = 1},
			['comboPoints'] = {
				[1] = {r = 0.69, g = 0.31, b = 0.31},
				[2] = {r = 0.65, g = 0.63, b = 0.34},
				[3] = {r = 0.33, g = 0.59, b = 0.33},
			},
			['DEATHKNIGHT'] = {r = 0, g = 1, b = 1},
			['PALADIN'] = {r = 228/255,g = 225/255,b = 16/255},
			['MAGE'] = {r = 0, g = 157/255, b = 255/255},
			['MONK'] = {
				[1] = {r = .57, g = .63, b = .35},
				[2] = {r = .47, g = .63, b = .35},
				[3] = {r = .37, g = .63, b = .35},
				[4] = {r = .27, g = .63, b = .33},
				[5] = {r = .17, g = .63, b = .33},
				[6] = {r = 12/255, g = 145/255, b = 58/255}
			},
			['WARLOCK'] = {r = 148/255, g = 130/255, b = 201/255}
		},
	},

	['units'] = {
		['player'] = {
			['enable'] = true,
			['orientation'] = "LEFT",
			['width'] = 270,
			['height'] = 38,
			['lowmana'] = 40,
			['combatfade'] = false,
			['healPrediction'] = false,
			['restIcon'] = true,
			["combatIcon"] = true,
			['threatStyle'] = 'GLOW',
			["smartAuraPosition"] = "DEBUFFS_ON_BUFFS",
			["colorOverride"] = "USE_DEFAULT",
			['health'] = {
				['text_format'] = '[healthcolor][health:current-percent]',
				['position'] = 'LEFT',
				['xOffset'] = 2,
				['yOffset'] = 0,
				['attachTextTo'] = 'Frame',
			},
			['power'] = {
				['enable'] = true,
				['text_format'] = '[powercolor][power:current]',
				['width'] = 'inset',
				['height'] = 2,
				['offset'] = 0,
				['position'] = 'RIGHT',
				['hideonnpc'] = false,
				['xOffset'] = -2,
				['yOffset'] = 0,
				['attachTextTo'] = 'Frame',
				['detachFromFrame'] = false,
				['detachedWidth'] = 250,
				['druidMana'] = true,
				["strataAndLevel"] = {
					["useCustomStrata"] = false,
					["frameStrata"] = "LOW",
					["useCustomLevel"] = false,
					["frameLevel"] = 1,
				},
				["parent"] = "FRAME",
			},
			['infoPanel'] = {
				['enable'] = false,
				['height'] = 20,
				["transparent"] = false,
			},
			['name'] = {
				['position'] = 'CENTER',
				['text_format'] = '[namecolor][name:long] [difficultycolor][level] [classification]',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['attachTextTo'] = 'Frame',
			},
			['pvp'] = {
				['position'] = 'TOPRIGHT',
				['text_format'] = '||cFFB04F4F[pvptimer][mouseover]||r',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['portrait'] = {
				['enable'] = true,
				['width'] = 45,
				['overlay'] = true,
				['camDistanceScale'] = 3,
				['rotation'] = 0,
				['style'] = '3D',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['buffs'] = {
				['enable'] = false,
				['perrow'] = 9,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'TOPLEFT',
				['fontSize'] = 14,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['clickThrough'] = false,
				['playerOnly'] = true,
				['selfBuffs'] = true,
				['useBlacklist'] = true,
				['useWhitelist'] = true,
				['noDuration'] = true,
				['onlyDispellable'] = false,
				['bossAuras'] = false,
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 1,
				['sizeOverride'] = 29,
			},
			['debuffs'] = {
				['enable'] = true,
				['perrow'] = 9,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'TOPRIGHT',
				['fontSize'] = 14,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['clickThrough'] = false,
				['playerOnly'] = false,
				['useBlacklist'] = true,
				['useWhitelist'] = false,
				['noDuration'] = false,
				['onlyDispellable'] = false,
				['bossAuras'] = false,
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['sizeOverride'] = 29,
			},
			['castbar'] = {
				['enable'] = true,
				['width'] = 270,
				['height'] = 24,
				['icon'] = true,
				['latency'] = true,
				['format'] = 'REMAINING',
				["ticks"] = true,
				['spark'] = true,
				['displayTarget'] = true,
				['iconSize'] = 42,
				['iconAttached'] = true,
				['insideInfoPanel'] = true,
				["iconAttachedTo"] = "Frame",
				["iconPosition"] = "LEFT",
				["iconXOffset"] = -10,
				["iconYOffset"] = 0,
			},
			['classbar'] = {
				['enable'] = true,
				['fill'] = 'filled',
				['height'] = 9,
				['detachFromFrame'] = true,
				['detachedWidth'] = 230,
				['autoHide'] = false,
				["parent"] = "FRAME",
				["verticalOrientation"] = false,
				["additionalPowerText"] = true,
			},
			['aurabar'] = {
				['enable'] = true,
				['anchorPoint'] = 'ABOVE',
				['attachTo'] = 'DEBUFFS',
				['maxBars'] = 8,
				['playerOnly'] = true,
				['selfBuffs'] = true,
				['useBlacklist'] = true,
				['useWhitelist'] = true,
				['noDuration'] = true,
				['onlyDispellable'] = false,
				['maxDuration'] = 120,
				['useFilter'] = '',
				['friendlyAuraType'] = 'HELPFUL',
				['enemyAuraType'] = 'HARMFUL',
				['height'] = 20,
				['sort'] = 'TIME_REMAINING',
				["uniformThreshold"] = 0,
			},
			['raidicon'] = {
				['enable'] = true,
				['size'] = 18,
				['attachTo'] = 'TOP',
				["attachToObject"] = "Frame",
				['xOffset'] = 0,
				['yOffset'] = 10,
			},
			['stagger'] = {
				['enable'] = true,
				['width'] = 10,
			},
		},
		['target'] = {
			['enable'] = true,
			['width'] = 270,
			['height'] = 38,
			['orientation'] = 'RIGHT',
			['threatStyle'] = 'GLOW',
			["smartAuraPosition"] = "DEBUFFS_ON_BUFFS",
			["colorOverride"] = "USE_DEFAULT",
			['rangeCheck'] = true,
			['healPrediction'] = false,
			['middleClickFocus'] = true,
			['health'] = {
				['text_format'] = '[healthcolor][health:current-percent]',
				['position'] = 'RIGHT',
				['xOffset'] = 1,
				['yOffset'] = 1,
				['attachTextTo'] = 'Health',
			},
			['power'] = {
				['enable'] = true,
				['text_format'] = '[powercolor][power:current]',
				['width'] = 'inset',
				['height'] = 2,
				['offset'] = 0,
				['position'] = 'LEFT',
				['hideonnpc'] = false,
				['xOffset'] = 1,
				['yOffset'] = 1,
				['detachFromFrame'] = false,
				['detachedWidth'] = 250,
				['attachTextTo'] = 'Health',
				["strataAndLevel"] = {
					["useCustomStrata"] = false,
					["frameStrata"] = "LOW",
					["useCustomLevel"] = false,
					["frameLevel"] = 1,
				},
				["parent"] = "FRAME",
			},
			['infoPanel'] = {
				['enable'] = false,
				['height'] = 20,
				["transparent"] = false,
			},
			['name'] = {
				['position'] = 'CENTER',
				['text_format'] = '[namecolor][name:medium] [difficultycolor][level] [classification]',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['attachTextTo'] = 'Health',
			},
			['portrait'] = {
				['enable'] = true,
				['width'] = 45,
				['overlay'] = true,
				['rotation'] = 0,
				['camDistanceScale'] = 3,
				['style'] = '3D',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['buffs'] = {
				['enable'] = true,
				['perrow'] = 9,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'TOPRIGHT',
				['fontSize'] = 14,
				['clickThrough'] = false,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['playerOnly'] = {friendly = true, enemy = false},
				['selfBuffs'] = {friendly = false, enemy = false},
				['useBlacklist'] = {friendly = true, enemy = true},
				['useWhitelist'] = {friendly = false, enemy = false},
				['noDuration'] = {friendly = false, enemy = false},
				['onlyDispellable'] = {friendly = false, enemy = false},
				['bossAuras'] = {friendly = true, enemy = true},
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 1,
				['sizeOverride'] = 29,
			},
			['debuffs'] = {
				['enable'] = true,
				['perrow'] = 9,
				['numrows'] = 1,
				['attachTo'] = 'BUFFS',
				['anchorPoint'] = 'TOPLEFT',
				['fontSize'] = 14,
				['clickThrough'] = false,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['playerOnly'] = {friendly = false, enemy = true},
				['useBlacklist'] = {friendly = true, enemy = true},
				['useWhitelist'] = {friendly = false, enemy = false},
				['noDuration'] = {friendly = false, enemy = false},
				['onlyDispellable'] = {friendly = false, enemy = false},
				['bossAuras'] = {friendly = true, enemy = true},
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 1,
				['sizeOverride'] = 29,
			},
			['castbar'] = {
				['enable'] = true,
				['width'] = 270,
				['height'] = 24,
				['icon'] = true,
				['format'] = 'REMAINING',
				['spark'] = true,
				['iconSize'] = 42,
				['iconAttached'] = true,
				['insideInfoPanel'] = true,
				["iconAttachedTo"] = "Frame",
				["iconPosition"] = "LEFT",
				["iconXOffset"] = -10,
				["iconYOffset"] = 0,
			},
			-- ['combobar'] = {
				-- ['enable'] = true,
				-- ['fill'] = 'filled',
				-- ['height'] = 9,
				-- ['detachFromFrame'] = true,
				-- ['detachedWidth'] = 230,
				-- ['autoHide'] = true,
			-- },
			['aurabar'] = {
				['enable'] = true,
				['anchorPoint'] = 'ABOVE',
				['attachTo'] = 'DEBUFFS',
				['maxBars'] = 8,
				['playerOnly'] = {friendly = true, enemy = true},
				['useBlacklist'] = {friendly = true, enemy = true},
				['useWhitelist'] = {friendly = false, enemy = false},
				['noDuration'] = {friendly = true, enemy = true},
				['selfBuffs'] = {friendly = true, enemy = true},
				['onlyDispellable'] = {friendly = false, enemy = false},
				['maxDuration'] = 300,
				['useFilter'] = '',
				['friendlyAuraType'] = 'HELPFUL',
				['enemyAuraType'] = 'HARMFUL',
				['height'] = 20,
				['sort'] = 'TIME_REMAINING',
				["uniformThreshold"] = 0,
			},
			['raidicon'] = {
				['enable'] = true,
				['size'] = 18,
				['attachTo'] = 'TOP',
				["attachToObject"] = "Frame",
				['xOffset'] = 0,
				['yOffset'] = 10,
			},
			['GPSArrow'] = {
				['enable'] = false,
				['size'] = 45,
				['xOffset'] = 0,
				['yOffset'] = 0,
				['onMouseOver'] = true,
				['outOfRange'] = true
			},
		},
		['targettarget'] = {
			['enable'] = true,
			['rangeCheck'] = true,
			['threatStyle'] = 'GLOW',
			['orientation'] = 'MIDDLE',
			["smartAuraPosition"] = "DISABLED",
			["colorOverride"] = "USE_DEFAULT",
			['width'] = 122,
			['height'] = 38,
			['health'] = {
				['text_format'] = '',
				['position'] = 'RIGHT',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['power'] = {
				['enable'] = true,
				['text_format'] = '',
				['width'] = 'inset',
				['height'] = 2,
				['offset'] = 0,
				['position'] = 'LEFT',
				['hideonnpc'] = false,
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['infoPanel'] = {
				['enable'] = false,
				['height'] = 14,
				["transparent"] = false,
			},
			['name'] = {
				['position'] = 'CENTER',
				['text_format'] = '[namecolor][name:short]',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['attachTextTo'] = 'Frame',
			},
			['portrait'] = {
				['enable'] = true,
				['width'] = 45,
				['overlay'] = true,
				['camDistanceScale'] = 3,
				['rotation'] = 0,
				['style'] = '3D',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['buffs'] = {
				['enable'] = true,
				['perrow'] = 1,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'LEFT',
				['fontSize'] = 14,
				['clickThrough'] = false,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['playerOnly'] = {friendly = true, enemy = false},
				['selfBuffs'] = {friendly = true, enemy = false},
				['useBlacklist'] = {friendly = true, enemy = true},
				['useWhitelist'] = {friendly = false, enemy = false},
				['noDuration'] = {friendly = true, enemy = false},
				['onlyDispellable'] = {friendly = false, enemy = false},
				['bossAuras'] = {friendly = true, enemy = true},
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['sizeOverride'] = 38,
			},
			['debuffs'] = {
				['enable'] = true,
				['perrow'] = 2,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'RIGHT',
				['fontSize'] = 14,
				['clickThrough'] = false,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['playerOnly'] = {friendly = false, enemy = true},
				['useBlacklist'] = {friendly = true, enemy = true},
				['useWhitelist'] = {friendly = false, enemy = false},
				['noDuration'] = {friendly = false, enemy = false},
				['onlyDispellable'] = {friendly = false, enemy = false},
				['bossAuras'] = {friendly = true, enemy = true},
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['sizeOverride'] = 38,
			},
			['raidicon'] = {
				['enable'] = true,
				['size'] = 18,
				['attachTo'] = 'TOP',
				["attachToObject"] = "Frame",
				['xOffset'] = 0,
				['yOffset'] = 10,
			},
		},
		['targettargettarget'] = {
			['enable'] = true,
			['rangeCheck'] = true,
			['orientation'] = "MIDDLE",
			['threatStyle'] = 'GLOW',
			["smartAuraPosition"] = "DISABLED",
			["colorOverride"] = "USE_DEFAULT",
			['width'] = 71,
			['height'] = 38,
			['health'] = {
				['text_format'] = '',
				['position'] = 'RIGHT',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['power'] = {
				['enable'] = true,
				['text_format'] = '',
				['width'] = 'inset',
				['height'] = 2,
				['offset'] = 0,
				['position'] = 'LEFT',
				['hideonnpc'] = false,
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['infoPanel'] = {
				['enable'] = false,
				['height'] = 12,
				["transparent"] = false,
			},
			['name'] = {
				['position'] = 'CENTER',
				['text_format'] = '[namecolor][name:short]',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['attachTextTo'] = 'Frame',
			},
			['portrait'] = {
				['enable'] = true,
				['width'] = 45,
				['overlay'] = true,
				['camDistanceScale'] = 3,
				['rotation'] = 0,
				['style'] = '3D',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['buffs'] = {
				['enable'] = true,
				['perrow'] = 1,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'LEFT',
				['fontSize'] = 14,
				['clickThrough'] = false,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['playerOnly'] = {friendly = true, enemy = false},
				['selfBuffs'] = {friendly = true, enemy = false},
				['useBlacklist'] = {friendly = true, enemy = true},
				['useWhitelist'] = {friendly = false, enemy = false},
				['noDuration'] = {friendly = true, enemy = false},
				['onlyDispellable'] = {friendly = false, enemy = false},
				['bossAuras'] = {friendly = true, enemy = true},
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['sizeOverride'] = 38,
			},
			['debuffs'] = {
				['enable'] = true,
				['perrow'] = 2,
				['numrows'] = 1,
				['attachTo'] = 'BUFFS',
				['anchorPoint'] = 'LEFT',
				['fontSize'] = 14,
				['clickThrough'] = false,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['playerOnly'] = {friendly = false, enemy = true},
				['useBlacklist'] = {friendly = true, enemy = true},
				['useWhitelist'] = {friendly = false, enemy = false},
				['noDuration'] = {friendly = false, enemy = false},
				['onlyDispellable'] = {friendly = false, enemy = false},
				['bossAuras'] = {friendly = true, enemy = true},
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['sizeOverride'] = 38,
			},
			['raidicon'] = {
				['enable'] = true,
				['size'] = 18,
				['attachTo'] = 'TOP',
				["attachToObject"] = "Frame",
				['xOffset'] = 0,
				['yOffset'] = 10,
			},
		},
		['focus'] = {
			['enable'] = true,
			['rangeCheck'] = true,
			['threatStyle'] = 'GLOW',
			['orientation'] = 'MIDDLE',
			["smartAuraPosition"] = "DISABLED",
			["colorOverride"] = "USE_DEFAULT",
			['width'] = 192,
			['height'] = 34,
			['healPrediction'] = false,
			['health'] = {
				['text_format'] = '[healthcolor][health:current-percent]',
				['position'] = 'LEFT',
				['xOffset'] = 1,
				['yOffset'] = 2,
				['attachTextTo'] = 'Health',
			},
			['power'] = {
				['enable'] = true,
				['text_format'] = '[powercolor][power:current]',
				['width'] = 'inset',
				['height'] = 2,
				['offset'] = 0,
				['position'] = 'RIGHT',
				['hideonnpc'] = false,
				['xOffset'] = 1,
				['yOffset'] = 2,
				['attachTextTo'] = 'Health',
			},
			['infoPanel'] = {
				['enable'] = false,
				['height'] = 14,
				["transparent"] = false,
			},
			['name'] = {
				['position'] = 'CENTER',
				['text_format'] = '[namecolor][name:medium]',
				['xOffset'] = 0,
				['yOffset'] = 2,
				['attachTextTo'] = 'Frame',
			},
			['portrait'] = {
				['enable'] = true,
				['width'] = 45,
				['overlay'] = true,
				['camDistanceScale'] = 3,
				['rotation'] = 0,
				['style'] = '3D',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['buffs'] = {
				['enable'] = true,
				['perrow'] = 7,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'TOPLEFT',
				['fontSize'] = 16,
				['clickThrough'] = false,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['playerOnly'] = {friendly = true, enemy = false},
				['selfBuffs'] = {friendly = true, enemy = false},
				['useBlacklist'] = {friendly = true, enemy = true},
				['useWhitelist'] = {friendly = false, enemy = false},
				['noDuration'] = {friendly = false, enemy = false},
				['onlyDispellable'] = {friendly = false, enemy = false},
				['bossAuras'] = {friendly = true, enemy = true},
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['sizeOverride'] = 0,
			},
			['debuffs'] = {
				['enable'] = true,
				['perrow'] = 7,
				['numrows'] = 1,
				['attachTo'] = 'BUFFS',
				['anchorPoint'] = 'TOPRIGHT',
				['fontSize'] = 16,
				['clickThrough'] = false,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['playerOnly'] = {friendly = false, enemy = true},
				['useBlacklist'] = {friendly = true, enemy = true},
				['useWhitelist'] = {friendly = false, enemy = false},
				['noDuration'] = {friendly = false, enemy = false},
				['onlyDispellable'] = {friendly = false, enemy = false},
				['bossAuras'] = {friendly = true, enemy = true},
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['sizeOverride'] = 0,
			},
			['castbar'] = {
				['enable'] = true,
				['width'] = 192,
				['height'] = 20,
				['icon'] = true,
				['format'] = 'REMAINING',
				['spark'] = true,
				['iconSize'] = 32,
				['iconAttached'] = true,
				['insideInfoPanel'] = true,
				["iconAttachedTo"] = "Frame",
				["iconPosition"] = "LEFT",
				["iconXOffset"] = -10,
				["iconYOffset"] = 0,
			},
			['aurabar'] = {
				['enable'] = false,
				['anchorPoint'] = 'ABOVE',
				['attachTo'] = 'FRAME',
				['maxBars'] = 3,
				['playerOnly'] = {friendly = false, enemy = true},
				['useBlacklist'] = {friendly = true, enemy = true},
				['useWhitelist'] = {friendly = false, enemy = false},
				['noDuration'] = {friendly = false, enemy = false},
				['onlyDispellable'] = {friendly = false, enemy = false},
				['selfBuffs'] = {friendly = true, enemy = true},
				['maxDuration'] = 120,
				['useFilter'] = '',
				['friendlyAuraType'] = 'HELPFUL',
				['enemyAuraType'] = 'HARMFUL',
				['height'] = 20,
				['sort'] = 'TIME_REMAINING',
				["uniformThreshold"] = 0,
			},
			['raidicon'] = {
				['enable'] = true,
				['size'] = 18,
				['attachTo'] = 'TOP',
				["attachToObject"] = "Frame",
				['xOffset'] = 0,
				['yOffset'] = 10,
			},
			['GPSArrow'] = {
				['enable'] = false,
				['size'] = 45,
				['xOffset'] = 0,
				['yOffset'] = 0,
				['onMouseOver'] = true,
				['outOfRange'] = true
			},
		},
		['focustarget'] = {
			['enable'] = true,
			['rangeCheck'] = true,
			['threatStyle'] = 'GLOW',
			['orientation'] = 'MIDDLE',
			["smartAuraPosition"] = "DISABLED",
			["colorOverride"] = "USE_DEFAULT",
			['width'] = 80,
			['height'] = 34,
			['health'] = {
				['text_format'] = '',
				['position'] = 'RIGHT',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['power'] = {
				['enable'] = true,
				['text_format'] = '',
				['width'] = 'inset',
				['height'] = 2,
				['offset'] = 0,
				['position'] = 'LEFT',
				['hideonnpc'] = false,
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['infoPanel'] = {
				['enable'] = false,
				['height'] = 12,
				["transparent"] = false,
			},
			['name'] = {
				['position'] = 'CENTER',
				['text_format'] = '[namecolor][name:short]',
				['xOffset'] = 0,
				['yOffset'] = 2,
				['attachTextTo'] = 'Frame',
			},
			['portrait'] = {
				['enable'] = true,
				['width'] = 45,
				['overlay'] = true,
				['camDistanceScale'] = 3,
				['rotation'] = 0,
				['style'] = '3D',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['buffs'] = {
				['enable'] = true,
				['perrow'] = 3,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'TOPRIGHT',
				['fontSize'] = 17,
				['clickThrough'] = false,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['playerOnly'] = {friendly = true, enemy = false},
				['selfBuffs'] = {friendly = true, enemy = false},
				['useBlacklist'] = {friendly = true, enemy = true},
				['useWhitelist'] = {friendly = false, enemy = false},
				['noDuration'] = {friendly = true, enemy = false},
				['onlyDispellable'] = {friendly = false, enemy = false},
				['bossAuras'] = {friendly = true, enemy = true},
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['sizeOverride'] = 0,
			},
			['debuffs'] = {
				['enable'] = true,
				['perrow'] = 3,
				['numrows'] = 1,
				['attachTo'] = 'BUFFS',
				['anchorPoint'] = 'TOPLEFT',
				['fontSize'] = 17,
				['clickThrough'] = false,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['playerOnly'] = {friendly = false, enemy = true},
				['useBlacklist'] = {friendly = true, enemy = true},
				['useWhitelist'] = {friendly = false, enemy = false},
				['noDuration'] = {friendly = false, enemy = false},
				['onlyDispellable'] = {friendly = false, enemy = false},
				['bossAuras'] = {friendly = true, enemy = true},
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['sizeOverride'] = 0,
			},
			['raidicon'] = {
				['enable'] = true,
				['size'] = 18,
				['attachTo'] = 'TOP',
				["attachToObject"] = "Frame",
				['xOffset'] = 0,
				['yOffset'] = 10,
			},
		},
		['pet'] = {
			['enable'] = true,
			['rangeCheck'] = true,
			['orientation'] = "MIDDLE",
			['threatStyle'] = 'GLOW',
			["smartAuraPosition"] = "DISABLED",
			["colorOverride"] = "USE_DEFAULT",
			['width'] = 122,
			['height'] = 38,
			['healPrediction'] = false,
			['health'] = {
				['text_format'] = '',
				['position'] = 'RIGHT',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['power'] = {
				['enable'] = true,
				['text_format'] = '',
				['width'] = 'inset',
				['height'] = 2,
				['offset'] = 0,
				['position'] = 'LEFT',
				['hideonnpc'] = false,
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['infoPanel'] = {
				['enable'] = false,
				['height'] = 12,
				["transparent"] = false,
			},
			['name'] = {
				['position'] = 'CENTER',
				['text_format'] = '[namecolor][name:short]',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['attachTextTo'] = 'Frame',
			},
			['portrait'] = {
				['enable'] = true,
				['width'] = 45,
				['overlay'] = true,
				['camDistanceScale'] = 3,
				['rotation'] = 0,
				['style'] = '3D',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['buffs'] = {
				['enable'] = true,
				['perrow'] = 1,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'RIGHT',
				['fontSize'] = 14,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['clickThrough'] = false,
				['playerOnly'] = true,
				['selfBuffs'] = true,
				['useBlacklist'] = true,
				['useWhitelist'] = false,
				['noDuration'] = true,
				['onlyDispellable'] = false,
				['bossAuras'] = true,
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['sizeOverride'] = 38,
			},
			['debuffs'] = {
				['enable'] = true,
				['perrow'] = 2,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'LEFT',
				['fontSize'] = 14,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['clickThrough'] = false,
				['playerOnly'] = false,
				['useBlacklist'] = true,
				['useWhitelist'] = false,
				['noDuration'] = false,
				['onlyDispellable'] = false,
				['bossAuras'] = true,
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['sizeOverride'] = 38,
			},
			['buffIndicator'] = {
				['enable'] = true,
				['size'] = 8,
				['fontSize'] = 14,
			},
			['castbar'] = {
				['enable'] = true,
				['width'] = 270,
				['height'] = 24,
				['icon'] = true,
				['format'] = 'REMAINING',
				['spark'] = true,
				['iconSize'] = 26,
				['iconAttached'] = true,
				['insideInfoPanel'] = true,
				["iconAttachedTo"] = "Frame",
				["iconPosition"] = "LEFT",
				["iconXOffset"] = -10,
				["iconYOffset"] = 0,
			},
		},
		['pettarget'] = {
			['enable'] = true,
			['rangeCheck'] = true,
			['threatStyle'] = 'GLOW',
			['orientation'] = 'MIDDLE',
			["smartAuraPosition"] = "DISABLED",
			["colorOverride"] = "USE_DEFAULT",
			['width'] = 71,
			['height'] = 38,
			['health'] = {
				['text_format'] = '',
				['position'] = 'RIGHT',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['power'] = {
				['enable'] = true,
				['text_format'] = '',
				['width'] = 'inset',
				['height'] = 2,
				['offset'] = 0,
				['position'] = 'LEFT',
				['hideonnpc'] = false,
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['infoPanel'] = {
				['enable'] = false,
				['height'] = 12,
				["transparent"] = false,
			},
			['name'] = {
				['position'] = 'CENTER',
				['text_format'] = '[namecolor][name:short]',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['attachTextTo'] = 'Frame',
			},
			['portrait'] = {
				['enable'] = true,
				['width'] = 45,
				['overlay'] = true,
				['camDistanceScale'] = 3,
				['rotation'] = 0,
				['style'] = '3D',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['buffs'] = {
				['enable'] = true,
				['perrow'] = 1,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'RIGHT',
				['fontSize'] = 14,
				['clickThrough'] = false,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['playerOnly'] = {friendly = true, enemy = false},
				['selfBuffs'] = {friendly = true, enemy = false},
				['useBlacklist'] = {friendly = true, enemy = true},
				['useWhitelist'] = {friendly = false, enemy = false},
				['noDuration'] = {friendly = true, enemy = false},
				['onlyDispellable'] = {friendly = false, enemy = false},
				['bossAuras'] = {friendly = true, enemy = true},
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['sizeOverride'] = 38,
			},
			['debuffs'] = {
				['enable'] = true,
				['perrow'] = 2,
				['numrows'] = 1,
				['attachTo'] = 'BUFFS',
				['anchorPoint'] = 'RIGHT',
				['fontSize'] = 14,
				['clickThrough'] = false,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['playerOnly'] = {friendly = false, enemy = true},
				['useBlacklist'] = {friendly = true, enemy = true},
				['useWhitelist'] = {friendly = false, enemy = false},
				['noDuration'] = {friendly = false, enemy = false},
				['onlyDispellable'] = {friendly = false, enemy = false},
				['bossAuras'] = {friendly = true, enemy = true},
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['sizeOverride'] = 38,
			},
		},
		['boss'] = {
			['enable'] = true,
			['rangeCheck'] = true,
			['growthDirection'] = 'DOWN',
			['orientation'] = 'RIGHT',
			["smartAuraPosition"] = "DISABLED",
			["colorOverride"] = "USE_DEFAULT",
			['width'] = 192,
			['height'] = 26,
			['spacing'] = 24,
			['targetGlow'] = true,
			['health'] = {
				['text_format'] = '[healthcolor][health:current-percent]',
				['position'] = 'RIGHT',
				['yOffset'] = 0,
				['xOffset'] = 0,
				['attachTextTo'] = 'frame',
			},
			['power'] = {
				['enable'] = false,
				['text_format'] = '[powercolor][power:current]',
				['width'] = 'inset',
				['height'] = 7,
				['offset'] = 0,
				['position'] = 'LEFT',
				['hideonnpc'] = false,
				['attachTextTo'] = 'frame',
				['xOffset'] = 4,
				['yOffset'] = 0,
			},
			['portrait'] = {
				['enable'] = true,
				['width'] = 45,
				['overlay'] = true,
				['rotation'] = 0,
				['camDistanceScale'] = 3,
				['style'] = '3D',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['infoPanel'] = {
				['enable'] = false,
				['height'] = 16,
				["transparent"] = false,
			},
			['name'] = {
				['position'] = 'CENTER',
				['text_format'] = '[namecolor][name:short]',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['attachTextTo'] = 'Frame',
			},
			['buffs'] = {
				['enable'] = true,
				['perrow'] = 4,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'TOPRIGHT',
				['fontSize'] = 14,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['clickThrough'] = false,
				['playerOnly'] = {friendly = false, enemy = false},
				['selfBuffs'] = {friendly = false, enemy = false},
				['useBlacklist'] = {friendly = true, enemy = true},
				['useWhitelist'] = {friendly = false, enemy = false},
				['noDuration'] = {friendly = false, enemy = false},
				['onlyDispellable'] = {friendly = false, enemy = false},
				['bossAuras'] = {friendly = true, enemy = true},
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['sizeOverride'] = 23,
			},
			['debuffs'] = {
				['enable'] = true,
				['perrow'] = 4,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'TOPLEFT',
				['fontSize'] = 14,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['clickThrough'] = false,
				['playerOnly'] = {friendly = true, enemy = true},
				['useBlacklist'] = {friendly = true, enemy = true},
				['useWhitelist'] = {friendly = false, enemy = false},
				['noDuration'] = {friendly = false, enemy = false},
				['onlyDispellable'] = {friendly = false, enemy = false},
				['bossAuras'] = {friendly = true, enemy = true},
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['sizeOverride'] = 23,
			},
			['castbar'] = {
				['enable'] = true,
				['width'] = 192,
				['height'] = 18,
				['icon'] = true,
				-- ['latency'] = true,
				['format'] = 'REMAINING',
				['spark'] = true,
				['iconSize'] = 32,
				['iconAttached'] = true,
				['insideInfoPanel'] = true,
				["iconAttachedTo"] = "Frame",
				["iconPosition"] = "LEFT",
				["iconXOffset"] = -10,
				["iconYOffset"] = 0,
			},
			['raidicon'] = {
				['enable'] = true,
				['size'] = 18,
				['attachTo'] = 'TOP',
				["attachToObject"] = "Frame",
				['xOffset'] = 0,
				['yOffset'] = 10,
			},
		},
		['arena'] = {
			['enable'] = true,
			['rangeCheck'] = true,
			['growthDirection'] = 'DOWN',
			['orientation'] = 'RIGHT',
			["smartAuraPosition"] = "DISABLED",
			['spacing'] = 24,
			['width'] = 192,
			['height'] = 26,
			['pvpSpecIcon'] = true,
			['healPrediction'] = true,
			['colorOverride'] = 'USE_DEFAULT',
			['targetGlow'] = true,
			['health'] = {
				['text_format'] = '[healthcolor][health:current]',
				['position'] = 'RIGHT',
				['yOffset'] = 0,
				['xOffset'] = 0,
				['attachTextTo'] = 'Frame',
			},
			['power'] = {
				['enable'] = true,
				['text_format'] = '[powercolor][power:current]',
				['width'] = 'filled',
				['height'] = 7,
				['offset'] = 0,
				['attachTextTo'] = 'Frame',
				['position'] = 'LEFT',
				['hideonnpc'] = false,
				['yOffset'] = 0,
				['xOffset'] = 32,
			},
			['infoPanel'] = {
				['enable'] = false,
				['height'] = 17,
				["transparent"] = false,
			},
			['name'] = {
				['position'] = 'CENTER',
				['text_format'] = '[namecolor][name:medium]',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['attachTextTo'] = 'Frame',
			},
			['portrait'] = {
				['enable'] = true,
				['width'] = 45,
				['overlay'] = true,
				['camDistanceScale'] = 3,
				['rotation'] = 0,
				['style'] = '3D',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['buffs'] = {
				['enable'] = true,
				['perrow'] = 4,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'LEFT',
				['fontSize'] = 14,
				['clickThrough'] = false,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['playerOnly'] = {friendly = false, enemy = false},
				['selfBuffs'] = {friendly = false, enemy = false},
				['useBlacklist'] = {friendly = false, enemy = false},
				['useWhitelist'] = {friendly = false, enemy = false},
				['noDuration'] = {friendly = false, enemy = false},
				['useFilter'] = 'TurtleBuffs',
				['onlyDispellable'] = {friendly = false, enemy = false},
				['bossAuras'] = {friendly = false, enemy = false},
				['sizeOverride'] = 23,
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['debuffs'] = {
				['enable'] = true,
				['perrow'] = 4,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'RIGHT',
				['fontSize'] = 14,
				['clickThrough'] = false,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['playerOnly'] = {friendly = false, enemy = false},
				['useBlacklist'] = {friendly = false, enemy = false},
				['useWhitelist'] = {friendly = false, enemy = false},
				['noDuration'] = {friendly = false, enemy = false},
				['useFilter'] = 'CCDebuffs',
				['onlyDispellable'] = {friendly = false, enemy = false},
				['bossAuras'] = {friendly = false, enemy = false},
				['sizeOverride'] = 23,
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['castbar'] = {
				['enable'] = true,
				['width'] = 192,
				['height'] = 18,
				['icon'] = true,
				-- ['latency'] = true,
				['format'] = 'REMAINING',
				['spark'] = true,
				['iconSize'] = 32,
				['iconAttached'] = true,
				['insideInfoPanel'] = true,
				["iconAttachedTo"] = "Frame",
				["iconPosition"] = "LEFT",
				["iconXOffset"] = -10,
				["iconYOffset"] = 0,
			},
			['pvpTrinket'] = {
				['enable'] = true,
				['position'] = 'RIGHT',
				['size'] = 46,
				['xOffset'] = 1,
				['yOffset'] = 0,
			},
		},
		['party'] = {
			['enable'] = true,
			['rangeCheck'] = true,
			['threatStyle'] = 'GLOW',
			['orientation'] = 'LEFT',
			['visibility'] = "[@raid6,exists][nogroup] hide;show",
			['growthDirection'] = 'UP_RIGHT',
			['horizontalSpacing'] = 0,
			['verticalSpacing'] = 26,
			['numGroups'] = 1,
			['groupsPerRowCol'] = 1,
			['groupBy'] = 'GROUP',
			['sortDir'] = 'ASC',
			['raidWideSorting'] = false,
			['invertGroupingOrder'] = false,
			['startFromCenter'] = false,
			["showPlayer"] = true,
			['healPrediction'] = false,
			['colorOverride'] = 'USE_DEFAULT',
			['width'] = 202,
			['height'] = 32,
			['targetGlow'] = true,
			['health'] = {
				['text_format'] = '[healthcolor][health:current-percent]',
				['position'] = 'LEFT',
				['orientation'] = 'HORIZONTAL',
				['attachTextTo'] = 'Frame',
				['frequentUpdates'] = false,
				['yOffset'] = 3,
				['xOffset'] = 6,
			},
			['power'] = {
				['enable'] = true,
				['text_format'] = '[powercolor][power:current]',
				['attachTextTo'] = 'Health',
				['width'] = 'inset',
				['height'] = 7,
				['offset'] = 0,
				['position'] = 'RIGHT',
				['hideonnpc'] = false,
				['yOffset'] = 3,
				['xOffset'] = -12,
			},
			['infoPanel'] = {
				['enable'] = false,
				['height'] = 15,
				["transparent"] = false,
			},
			['name'] = {
				['position'] = 'CENTER',
				['text_format'] = '[namecolor][name:medium] [difficultycolor][smartlevel]',
				['xOffset'] = 0,
				['yOffset'] = 3,
				['attachTextTo'] = 'Frame',
			},
			['portrait'] = {
				['enable'] = true,
				['width'] = 45,
				['overlay'] = true,
				['camDistanceScale'] = 3,
				['rotation'] = 0,
				['style'] = '3D',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['buffs'] = {
				['enable'] = true,
				['perrow'] = 4,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'TOPLEFT',
				['fontSize'] = 14,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['countFontSize'] = 14,
				['clickThrough'] = false,
				['playerOnly'] = true,
				['selfBuffs'] = true,
				['useBlacklist'] = true,
				['useWhitelist'] = false,
				['noDuration'] = true,
				['onlyDispellable'] = false,
				['bossAuras'] = true,
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['sizeOverride'] = 24,
			},
			['debuffs'] = {
				['enable'] = true,
				['perrow'] = 4,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'TOPRIGHT',
				['fontSize'] = 14,
				['countFontSize'] = 14,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['clickThrough'] = false,
				['playerOnly'] = false,
				['useBlacklist'] = true,
				['useWhitelist'] = false,
				['noDuration'] = false,
				['onlyDispellable'] = false,
				['bossAuras'] = true,
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
				['sizeOverride'] = 24,
			},
			['buffIndicator'] = {
				['enable'] = true,
				['size'] = 8,
				['fontSize'] = 14,
				['profileSpecific'] = false,
			},
			['rdebuffs'] = {
				['enable'] = true,
				["showDispellableDebuff"] = true,
				['fontSize'] = 10,
				["font"] = "Arial Narrow",
				["fontOutline"] = "OUTLINE",
				['size'] = 26,
				['xOffset'] = 0,
				['yOffset'] = 0,
				['duration'] = {
					['position'] = "CENTER",
					['xOffset'] = 0,
					['yOffset'] = 0,
					['color'] = {r = 1, g = 0.9, b = 0}
				},
				['stack'] = {
					['position'] = "BOTTOMRIGHT",
					['xOffset'] = 0,
					['yOffset'] = 2,
					['color'] = {r = 1, g = 0.9, b = 0}
				},
			},
			['roleIcon'] = {
				['enable'] = true,
				['position'] = 'RIGHT',
				["attachTo"] = "Health",
				["xOffset"] = 0,
				["yOffset"] = 3,
				['size'] = 15,
				["tank"] = true,
				["healer"] = true,
				["damager"] = true,
			},
			['raidRoleIcons'] = {
				['enable'] = true,
				['position'] = 'TOPLEFT',
			},
			['petsGroup'] = {
				['enable'] = true,
				['width'] = 90,
				['height'] = 32,
				['anchorPoint'] = 'RIGHT',
				['xOffset'] = 4,
				['yOffset'] = 0,
				['name'] = {
					['position'] = 'CENTER',
					['text_format'] = '[namecolor][name:short]',
					['xOffset'] = 0,
					['yOffset'] = 0,
					['attachTextTo'] = 'Frame',
				},
			},
			['targetsGroup'] = {
				['enable'] = true,
				['width'] = 90,
				['height'] = 32,
				['anchorPoint'] = 'RIGHT',
				['xOffset'] = 98,
				['yOffset'] = 0,
				['name'] = {
					['position'] = 'CENTER',
					['text_format'] = '[namecolor][name:short]',
					['xOffset'] = 0,
					['yOffset'] = 0,
					['attachTextTo'] = 'Frame',
				},
			},
			['raidicon'] = {
				['enable'] = true,
				['size'] = 18,
				['attachTo'] = 'TOP',
				["attachToObject"] = "Frame",
				['xOffset'] = 0,
				['yOffset'] = 10,
			},
			['GPSArrow'] = {
				['enable'] = true,
				['size'] = 45,
				['xOffset'] = 0,
				['yOffset'] = 0,
				['onMouseOver'] = true,
				['outOfRange'] = true
			},
		},
		['raid'] = {
			['enable'] = true,
			['rangeCheck'] = true,
			['threatStyle'] = 'GLOW',
			['orientation'] = 'MIDDLE',
			['visibility'] = '[@raid6,noexists][@raid26,exists] hide;show',
			['growthDirection'] = 'RIGHT_DOWN',
			['horizontalSpacing'] = 1,
			['verticalSpacing'] = 1,
			['numGroups'] = 6,
			['groupsPerRowCol'] = 1,
			['groupBy'] = 'GROUP',
			['sortDir'] = 'ASC',
			["showPlayer"] = true,
			['healPrediction'] = false,
			['colorOverride'] = 'USE_DEFAULT',
			['width'] = 81,
			['height'] = 32,
			['targetGlow'] = true,
			['health'] = {
				['text_format'] = '[healthcolor][health:deficit]',
				['position'] = 'BOTTOM',
				['orientation'] = 'HORIZONTAL',
				['attachTextTo'] = 'Health',
				['frequentUpdates'] = false,
				['yOffset'] = 8,
				['xOffset'] = 0,
			},
			['power'] = {
				['enable'] = true,
				['text_format'] = '',
				['width'] = 'inset',
				['height'] = 7,
				['offset'] = 0,
				['position'] = 'BOTTOMRIGHT',
				['hideonnpc'] = false,
				['yOffset'] = 0,
				['xOffset'] = 0,
			},
			['infoPanel'] = {
				['enable'] = false,
				['height'] = 12,
				["transparent"] = false,
			},
			['name'] = {
				['position'] = 'CENTER',
				['attachTextTo'] = 'frame',
				['text_format'] = '[namecolor][name:short]',
				['yOffset'] = 3,
				['xOffset'] = 0,
			},
			['portrait'] = {
				['enable'] = false,
				['width'] = 45,
				['overlay'] = false,
				['camDistanceScale'] = 2,
				['rotation'] = 0,
				['style'] = '3D',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['buffs'] = {
				['enable'] = false,
				['perrow'] = 3,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'LEFT',
				['fontSize'] = 14,
				['countFontSize'] = 10,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['clickThrough'] = false,
				['playerOnly'] = true,
				['selfBuffs'] = true,
				['useBlacklist'] = true,
				['useWhitelist'] = false,
				['noDuration'] = true,
				['onlyDispellable'] = false,
				['bossAuras'] = true,
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['debuffs'] = {
				['enable'] = false,
				['perrow'] = 3,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'RIGHT',
				['fontSize'] = 14,
				['countFontSize'] = 10,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['clickThrough'] = false,
				['playerOnly'] = false,
				['useBlacklist'] = true,
				['useWhitelist'] = false,
				['noDuration'] = false,
				['onlyDispellable'] = false,
				['bossAuras'] = true,
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['buffIndicator'] = {
				['enable'] = true,
				['size'] = 8,
				['fontSize'] = 14,
				['profileSpecific'] = false,
			},
			['rdebuffs'] = {
				['enable'] = true,
				["showDispellableDebuff"] = true,
				['fontSize'] = 14,
				["font"] = "Arial Narrow",
				["fontOutline"] = "OUTLINE",
				['size'] = 26,
				['xOffset'] = 0,
				['yOffset'] = 2,
				['duration'] = {
					['position'] = "CENTER",
					['xOffset'] = 0,
					['yOffset'] = 0,
					['color'] = {r = 1, g = 0.9, b = 0}
				},
				['stack'] = {
					['position'] = "BOTTOMRIGHT",
					['xOffset'] = 0,
					['yOffset'] = 2,
					['color'] = {r = 1, g = 0.9, b = 0}
				},
			},
			['roleIcon'] = {
				['enable'] = true,
				['position'] = 'RIGHT',
				["attachTo"] = "Health",
				["xOffset"] = -2,
				["yOffset"] = 3,
				['size'] = 15,
				["tank"] = true,
				["healer"] = true,
				["damager"] = true,
			},
			['raidRoleIcons'] = {
				['enable'] = true,
				['position'] = 'TOPLEFT',
			},
			['raidicon'] = {
				['enable'] = true,
				['size'] = 18,
				['attachTo'] = 'TOP',
				["attachToObject"] = "Frame",
				['xOffset'] = 0,
				['yOffset'] = 10,
			},
			['GPSArrow'] = {
				['enable'] = true,
				['size'] = 40,
				['xOffset'] = 0,
				['yOffset'] = 0,
				['onMouseOver'] = true,
				['outOfRange'] = true
			},
		},
		['raid40'] = {
			['enable'] = true,
			['rangeCheck'] = true,
			['threatStyle'] = 'GLOW',
			['orientation'] = 'MIDDLE',
			['visibility'] = '[@raid26,noexists] hide;show',
			['growthDirection'] = 'RIGHT_DOWN',
			['horizontalSpacing'] = 1,
			['verticalSpacing'] = 1,
			['numGroups'] = 8,
			['groupsPerRowCol'] = 1,
			['groupBy'] = 'GROUP',
			['sortDir'] = 'ASC',
			["showPlayer"] = true,
			['healPrediction'] = false,
			['colorOverride'] = 'USE_DEFAULT',
			['width'] = 81,
			['height'] = 32,
			['targetGlow'] = true,
			['health'] = {
				['text_format'] = '[healthcolor][health:deficit]',
				['position'] = 'BOTTOM',
				['orientation'] = 'HORIZONTAL',
				['attachTextTo'] = 'Health',
				['frequentUpdates'] = false,
				['yOffset'] = 8,
				['xOffset'] = 0,
			},
			['power'] = {
				['enable'] = true,
				['text_format'] = '',
				['width'] = 'inset',
				['height'] = 7,
				['offset'] = 0,
				['position'] = 'BOTTOMRIGHT',
				['hideonnpc'] = false,
				['yOffset'] = 0,
				['xOffset'] = 0,
			},
			['infoPanel'] = {
				['enable'] = false,
				['height'] = 12,
				["transparent"] = false,
			},
			['name'] = {
				['position'] = 'CENTER',
				['attachTextTo'] = 'Frame',
				['text_format'] = '[namecolor][name:short]',
				['yOffset'] = 3,
				['xOffset'] = 0,
			},
			['portrait'] = {
				['enable'] = false,
				['width'] = 45,
				['overlay'] = true,
				['camDistanceScale'] = 3,
				['rotation'] = 0,
				['style'] = '3D',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['buffs'] = {
				['enable'] = false,
				['perrow'] = 3,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'LEFT',
				['fontSize'] = 14,
				['countFontSize'] = 10,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['clickThrough'] = false,
				['playerOnly'] = true,

				['selfBuffs'] = true,
				['useBlacklist'] = true,
				['useWhitelist'] = false,
				['noDuration'] = true,
				['onlyDispellable'] = false,
				['bossAuras'] = true,
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['debuffs'] = {
				['enable'] = false,
				['perrow'] = 3,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'RIGHT',
				['fontSize'] = 14,
				['countFontSize'] = 10,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['clickThrough'] = false,
				['playerOnly'] = false,
				['useBlacklist'] = true,
				['useWhitelist'] = false,
				['noDuration'] = false,
				['onlyDispellable'] = false,
				['bossAuras'] = true,
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['rdebuffs'] = {
				['enable'] = true,
				["showDispellableDebuff"] = true,
				['fontSize'] = 14,
				["font"] = "Arial Narrow",
				["fontOutline"] = "OUTLINE",
				['size'] = 26,
				['xOffset'] = 0,
				['yOffset'] = 2,
				['duration'] = {
					['position'] = "CENTER",
					['xOffset'] = 0,
					['yOffset'] = 0,
					['color'] = {r = 1, g = 0.9, b = 0}
				},
				['stack'] = {
					['position'] = "BOTTOMRIGHT",
					['xOffset'] = 0,
					['yOffset'] = 2,
					['color'] = {r = 1, g = 0.9, b = 0}
				},
			},
			['roleIcon'] = {
				['enable'] = true,
				['position'] = 'RIGHT',
				["attachTo"] = "frame",
				["xOffset"] = -2,
				["yOffset"] = 3,
				['size'] = 15,
				["tank"] = true,
				["healer"] = true,
				["damager"] = true,
			},
			['raidRoleIcons'] = {
				['enable'] = true,
				['position'] = 'TOPLEFT',
			},
			['buffIndicator'] = {
				['enable'] = true,
				['size'] = 8,
				['fontSize'] = 14,
				['profileSpecific'] = false,
			},
			['raidicon'] = {
				['enable'] = true,
				['size'] = 18,
				['attachTo'] = 'TOP',
				["attachToObject"] = "Frame",
				['xOffset'] = 0,
				['yOffset'] = 10,
			},
			['GPSArrow'] = {
				['enable'] = true,
				['size'] = 40,
				['xOffset'] = 0,
				['yOffset'] = 0,
				['onMouseOver'] = true,
				['outOfRange'] = true
			},
		},
		['raidpet'] = {
			['enable'] = true,
			['rangeCheck'] = true,
			['orientation'] = "MIDDLE",
			['threatStyle'] = 'GLOW',
			['visibility'] = '[group:raid] show; hide',
			['growthDirection'] = 'RIGHT_DOWN',
			['horizontalSpacing'] = 1,
			['verticalSpacing'] = 1,
			['numGroups'] = 2,
			['groupsPerRowCol'] = 1,
			['groupBy'] = 'PETNAME',
			['sortDir'] = 'ASC',
			['raidWideSorting'] = true,
			['invertGroupingOrder'] = false,
			['startFromCenter'] = false,
			['healPrediction'] = false,
			['colorOverride'] = 'USE_DEFAULT',
			['width'] = 81,
			['height'] = 30,
			['targetGlow'] = true,
			['health'] = {
				['text_format'] = '[healthcolor][health:deficit]',
				['position'] = 'BOTTOM',
				['orientation'] = 'HORIZONTAL',
				['frequentUpdates'] = true,
				['yOffset'] = 0,
				['xOffset'] = 0,
				['attachTextTo'] = 'Health',
			},
			['name'] = {
				['position'] = 'TOP',
				['text_format'] = '[namecolor][name:short]',
				['yOffset'] = 0,
				['xOffset'] = 0,
				['attachTextTo'] = 'Health',
			},
			['portrait'] = {
				['enable'] = false,
				['width'] = 45,
				['overlay'] = true,
				['camDistanceScale'] = 3,
				['rotation'] = 0,
				['style'] = '3D',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['buffs'] = {
				['enable'] = false,
				['perrow'] = 3,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'LEFT',
				['fontSize'] = 10,
				['countFontSize'] = 10,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['clickThrough'] = false,
				['playerOnly'] = true,

				['selfBuffs'] = true,
				['useBlacklist'] = true,
				['useWhitelist'] = false,
				['noDuration'] = true,
				['onlyDispellable'] = false,
				['bossAuras'] = true,
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['debuffs'] = {
				['enable'] = false,
				['perrow'] = 3,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'RIGHT',
				['fontSize'] = 10,
				['countFontSize'] = 10,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['clickThrough'] = false,
				['playerOnly'] = false,
				['useBlacklist'] = true,
				['useWhitelist'] = false,
				['noDuration'] = false,
				['onlyDispellable'] = false,
				['bossAuras'] = true,
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 0,
			},
			['buffIndicator'] = {
				['enable'] = true,
				['size'] = 8,
				['fontSize'] = 10,
			},
			['rdebuffs'] = {
				['enable'] = true,
				["showDispellableDebuff"] = true,
				['fontSize'] = 10,
				["font"] = "Arial Narrow",
				["fontOutline"] = "OUTLINE",
				['size'] = 26,
				['xOffset'] = 0,
				['yOffset'] = 2,
				['duration'] = {
					['position'] = "CENTER",
					['xOffset'] = 0,
					['yOffset'] = 0,
					['color'] = {r = 1, g = 0.9, b = 0}
				},
				['stack'] = {
					['position'] = "BOTTOMRIGHT",
					['xOffset'] = 0,
					['yOffset'] = 2,
					['color'] = {r = 1, g = 0.9, b = 0}
				},
			},
			['raidicon'] = {
				['enable'] = true,
				['size'] = 18,
				['attachTo'] = 'TOP',
				["attachToObject"] = "Frame",
				['xOffset'] = 0,
				['yOffset'] = 10,
			},
		},
		-- ['bodyguard'] = {
			-- ['enable'] = true,
			-- ['width'] = 135,
			-- ['height'] = 38,
			-- ["colorOverride"] = "USE_DEFAULT",
		-- },
		['tank'] = {
			['enable'] = true,
			['orientation'] = "LEFT",
			['threatStyle'] = 'GLOW',
			["colorOverride"] = "USE_DEFAULT",
			['rangeCheck'] = true,
			['width'] = 120,
			['height'] = 28,
			["disableDebuffHighlight"] = true,
			["verticalSpacing"] = 7,
			['buffs'] = {
				['enable'] = false,
				['perrow'] = 6,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'TOPLEFT',
				['fontSize'] = 10,
				['countFontSize'] = 10,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['clickThrough'] = false,
				['playerOnly'] = false,
				['selfBuffs'] = false,
				['useBlacklist'] = false,
				['useWhitelist'] = false,
				['noDuration'] = false,
				['onlyDispellable'] = false,
				['bossAuras'] = false,
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 2,
			},
			['debuffs'] = {
				['enable'] = false,
				['perrow'] = 6,
				['numrows'] = 1,
				['attachTo'] = 'BUFFS',
				['anchorPoint'] = 'TOPRIGHT',
				['fontSize'] = 10,
				['countFontSize'] = 10,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['clickThrough'] = false,
				['playerOnly'] = false,
				['useBlacklist'] = false,
				['useWhitelist'] = false,
				['noDuration'] = false,
				['onlyDispellable'] = false,
				['bossAuras'] = false,
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 1,
			},
			['buffIndicator'] = {
				['enable'] = true,
				['size'] = 8,
				['fontSize'] = 10,
				['profileSpecific'] = false,
			},
			['rdebuffs'] = {
				['enable'] = true,
				["showDispellableDebuff"] = true,
				['fontSize'] = 10,
				["font"] = "Arial Narrow",
				["fontOutline"] = "OUTLINE",
				['size'] = 26,
				['xOffset'] = 0,
				['yOffset'] = 0,
				['duration'] = {
					['position'] = "CENTER",
					['xOffset'] = 0,
					['yOffset'] = 0,
					['color'] = {r = 1, g = 0.9, b = 0}
				},
				['stack'] = {
					['position'] = "BOTTOMRIGHT",
					['xOffset'] = 0,
					['yOffset'] = 2,
					['color'] = {r = 1, g = 0.9, b = 0}
				},
			},
			['targetsGroup'] = {
				['enable'] = true,
				['anchorPoint'] = 'RIGHT',
				['xOffset'] = 1,
				['yOffset'] = 0,
				['width'] = 120,
				['height'] = 28,
				["colorOverride"] = "USE_DEFAULT",
			},
		},
		['assist'] = {
			['enable'] = true,
			['orientation'] = "LEFT",
			['threatStyle'] = 'GLOW',
			["colorOverride"] = "USE_DEFAULT",
			['rangeCheck'] = true,
			['width'] = 120,
			['height'] = 28,
			["disableDebuffHighlight"] = true,
			["verticalSpacing"] = 7,
			['buffs'] = {
				['enable'] = false,
				['perrow'] = 6,
				['numrows'] = 1,
				['attachTo'] = 'FRAME',
				['anchorPoint'] = 'TOPLEFT',
				['fontSize'] = 10,
				['countFontSize'] = 10,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['clickThrough'] = false,
				['playerOnly'] = false,
				['selfBuffs'] = false,
				['useBlacklist'] = false,
				['useWhitelist'] = false,
				['noDuration'] = false,
				['onlyDispellable'] = false,
				['bossAuras'] = false,
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 2,
			},
			['debuffs'] = {
				['enable'] = false,
				['perrow'] = 6,
				['numrows'] = 1,
				['attachTo'] = 'BUFFS',
				['anchorPoint'] = 'TOPRIGHT',
				['fontSize'] = 10,
				['countFontSize'] = 10,
				['sortMethod'] = 'TIME_REMAINING',
				['sortDirection'] = 'DESCENDING',
				['clickThrough'] = false,
				['playerOnly'] = false,
				['useBlacklist'] = false,
				['useWhitelist'] = false,
				['noDuration'] = false,
				['onlyDispellable'] = false,
				['bossAuras'] = false,
				['useFilter'] = '',
				['xOffset'] = 0,
				['yOffset'] = 1,
			},
			['buffIndicator'] = {
				['enable'] = true,
				['size'] = 8,
				['fontSize'] = 10,
				['profileSpecific'] = false,
			},
			['rdebuffs'] = {
				['enable'] = true,
				["showDispellableDebuff"] = true,
				['fontSize'] = 10,
				["font"] = "Arial Narrow",
				["fontOutline"] = "OUTLINE",
				['size'] = 26,
				['xOffset'] = 0,
				['yOffset'] = 0,
				['duration'] = {
					['position'] = "CENTER",
					['xOffset'] = 0,
					['yOffset'] = 0,
					['color'] = {r = 1, g = 0.9, b = 0}
				},
				['stack'] = {
					['position'] = "BOTTOMRIGHT",
					['xOffset'] = 0,
					['yOffset'] = 2,
					['color'] = {r = 1, g = 0.9, b = 0}
				},
			},
			['targetsGroup'] = {
				['enable'] = true,
				['anchorPoint'] = 'RIGHT',
				['xOffset'] = 1,
				['yOffset'] = 0,
				['width'] = 120,
				['height'] = 28,
				["colorOverride"] = "USE_DEFAULT",
			},
		},
	},
}

--Cooldown
P["cooldown"] = {
	threshold = 3,
	expiringColor = { r = 1, g = 0, b = 0 },
	secondsColor = { r = 1, g = 1, b = 0 },
	minutesColor = { r = 1, g = 1, b = 1 },
	hoursColor = { r = 0.4, g = 1, b = 1 },
	daysColor = { r = 0.4, g = 0.4, b = 1 },
}

--Actionbar
P["actionbar"] = {
	['font'] = 'AgencyFB Bold',
	['fontSize'] = 12,
	['fontOutline'] = 'OUTLINE',
	["macrotext"] = true,
	["hotkeytext"] = true,
	['noRangeColor'] = { r = 0.8, g = 0.1, b = 0.1 },
	['noPowerColor'] = { r = 0.5, g = 0.5, b = 1 },
	['keyDown'] = true,
	['movementModifier'] = 'SHIFT',
	['microbar'] = {
		['enabled'] = true,
		['mouseover'] = true,
		['buttonsPerRow'] = 12,
		['alpha'] = 1,
	},

	['globalFadeAlpha'] = 0,
	['lockActionBars'] = true,

	['bar1'] = {
		['enabled'] = true,
		['buttons'] = 12,
		['mouseover'] = false,
		['buttonsPerRow'] = 12,
		['point'] = 'BOTTOMLEFT',
		['backdrop'] = false,
		['heightMult'] = 1,
		['widthMult'] = 1,
		["buttonsize"] = 33,
		["buttonspacing"] = 1,
		["backdropSpacing"] = 1,
		['alpha'] = 1,
		['inheritGlobalFade'] = false,
		['showGrid'] = true,
		['paging'] = {
			["DRUID"] = "[bonusbar:1,nostealth] 7; [bonusbar:1,stealth] 8; [bonusbar:2] 8; [bonusbar:3] 9; [bonusbar:4] 10;",
			["PRIEST"] = "[bonusbar:1] 7;",
			["ROGUE"] = "[stance:1] 7;  [stance:2] 7; [stance:3] 7;", -- set to "[stance:1] 7; [stance:3] 10;" if you want a shadow dance bar
			["MONK"] = "[bonusbar:1] 7; [bonusbar:2] 8; [bonusbar:3] 9;",
			["WARRIOR"] = "[bonusbar:1] 7; [bonusbar:2] 8;"
		},
		['visibility'] = "[petbattle] hide; show",
	},
	['bar2'] = {
		['enabled'] = true,
		['mouseover'] = false,
		['buttons'] = 12,
		['buttonsPerRow'] = 12,
		['point'] = 'BOTTOMLEFT',
		['backdrop'] = false,
		['heightMult'] = 1,
		['widthMult'] = 1,
		["buttonsize"] = 33,
		["buttonspacing"] = 1,
		["backdropSpacing"] = 1,
		['alpha'] = 1,
		['inheritGlobalFade'] = false,
		['showGrid'] = true,
		['paging'] = {},
		['visibility'] = "[vehicleui] hide; [overridebar] hide; [petbattle] hide; show",
	},
	['bar3'] = {
		['enabled'] = true,
		['mouseover'] = false,
		['buttons'] = 12,
		['buttonsPerRow'] = 6,
		['point'] = 'BOTTOMLEFT',
		['backdrop'] = false,
		['heightMult'] = 1,
		['widthMult'] = 1,
		["buttonsize"] = 33,
		["buttonspacing"] = 1,
		["backdropSpacing"] = 1,
		['alpha'] = 1,
		['inheritGlobalFade'] = false,
		['showGrid'] = true,
		['paging'] = {},
		['visibility'] = "[vehicleui] hide; [overridebar] hide; [petbattle] hide; show",
	},
	['bar4'] = {
		['enabled'] = true,
		['mouseover'] = false,
		['buttons'] = 12,
		['buttonsPerRow'] = 1,
		['point'] = 'TOPRIGHT',
		['backdrop'] = false,
		['heightMult'] = 1,
		['widthMult'] = 1,
		["buttonsize"] = 33,
		["buttonspacing"] = 1,
		["backdropSpacing"] = 1,
		['alpha'] = 1,
		['inheritGlobalFade'] = false,
		['showGrid'] = true,
		['paging'] = {},
		['visibility'] = "[vehicleui] hide; [overridebar] hide; [petbattle] hide; show",
	},
	['bar5'] = {
		['enabled'] = true,
		['mouseover'] = false,
		['buttons'] = 12,
		['buttonsPerRow'] = 6,
		['point'] = 'BOTTOMLEFT',
		['backdrop'] = false,
		['heightMult'] = 1,
		['widthMult'] = 1,
		["buttonsize"] = 33,
		["buttonspacing"] = 1,
		["backdropSpacing"] = 1,
		['alpha'] = 1,
		['inheritGlobalFade'] = false,
		['showGrid'] = true,
		['paging'] = {},
		['visibility'] = "[vehicleui] hide; [overridebar] hide; [petbattle] hide; show",
	},
	['bar6'] = {
		['enabled'] = false,
		['mouseover'] = false,
		['buttons'] = 12,
		['buttonsPerRow'] = 1,
		['point'] = 'TOPRIGHT',
		['backdrop'] = false,
		['heightMult'] = 1,
		['widthMult'] = 1,
		["buttonsize"] = 33,
		["buttonspacing"] = 1,
		["backdropSpacing"] = 1,
		['alpha'] = 1,
		['inheritGlobalFade'] = false,
		['showGrid'] = true,
		['paging'] = {},
		['visibility'] = "[vehicleui] hide; [overridebar] hide; [petbattle] hide; show",
	},
	['barPet'] = {
		['enabled'] = true,
		['mouseover'] = false,
		['buttons'] = NUM_PET_ACTION_SLOTS,
		['buttonsPerRow'] = 10,
		['point'] = 'TOPRIGHT',
		['backdrop'] = false,
		['heightMult'] = 1,
		['widthMult'] = 1,
		["buttonsize"] = 33,
		["buttonspacing"] = 1,
		["backdropSpacing"] = 1,
		['alpha'] = 1,
		['inheritGlobalFade'] = false,
		['visibility'] = "[petbattle] hide;[pet,novehicleui,nooverridebar,nopossessbar] show;hide",
	},
	['stanceBar'] = {
		['enabled'] = true,
		['style'] = 'darkenInactive',
		['mouseover'] = false,
		['buttonsPerRow'] = NUM_STANCE_SLOTS,
		['buttons'] = NUM_STANCE_SLOTS,
		['point'] = 'TOPLEFT',
		['backdrop'] = false,
		['heightMult'] = 1,
		['widthMult'] = 1,
		["buttonsize"] = 33,
		["buttonspacing"] = 1,
		["backdropSpacing"] = 1,
		['alpha'] = 1,
		['inheritGlobalFade'] = false,
	},
	['extraActionButton'] = {
		['alpha'] = 1,
		["scale"] = 1,
		['inheritGlobalFade'] = false,
	},
};